name: Zip Source Files

on: [push]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # Ensure we have full history and can commit back to the repository
        fetch-depth: 0
    
    - name: Zip C++ Source Files
      run: zip sscbs_analytics.zip **.cc **.cpp
    
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    
    - name: Commit and Push Zip File
      run: |
        git add sscbs_analytics.zip
        git commit -m "Auto-generate source code zip file"
        git push
