name: Zip Source Files

on: [push]

permissions:
  contents: write  # This gives write permission to the GITHUB_TOKEN

jobs:
  zip-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Zip C++ Source Files
      run: zip sscbs_analytics.zip **.cc **.cpp
    
    - name: Commit and Push Zip File
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add sscbs_analytics.zip
        git commit -m "Auto-generate source code zip file"
        git push
