name: Zip Source Files

on: [push]

permissions:
  contents: write # This gives write permission to the GITHUB_TOKEN

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip python/python notebook Source Files, and computer grahics practical
        run: |
          rm **zip
          zip sscbs_analytics.zip **.py **.ipynb **.txt
          zip -r sscbs_analytics_cg.zip c_graphics/**.c c_graphics/3d_transformation/**.c
          cd dhruv_python
          zip sscbs_analytics_py_dhr.zip **.py 

      - name: Commit and Push Zip File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add sscbs_analytics.zip sscbs_analytics_cg.zip ./dhruv_python/sscbs_analytics_py_dhr.zip 
          git commit -m "Auto-generate source code zip file"
          git push
